version: '3.8'

services:
  gaybot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gaybot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount logs directory if you add logging
      - ./logs:/app/logs
    networks:
      - bot-network
    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  bot-network:
    driver: bridge
